# Generated by Django 5.1.15 on 2026-10-02 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('LEAVE', 'Leave'), ('PAYROLL', 'Payroll'), ('DOCUMENT', 'Document'), ('ATTENDANCE', 'Attendance'), ('GOAL', 'Goal'), ('ANNOUNCEMENT', 'Announcement'), ('BIRTHDAY', 'Birthday'), ('ANNIVERSARY', 'Anniversary'), ('INTERVIEW', 'Interview'), ('ONBOARDING', 'Onboarding'), ('RECOGNITION', 'Recognition'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
            },
        ),
    ]
