# Generated by Django 5.1.15 on 2026-10-02 02:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('audience', models.CharField(choices=[('COMPANY', 'Company'), ('DEPARTMENT', 'Department')], default='COMPANY', max_length=12)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('IMPORTANT', 'Important'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.department')),
            ],
            options={
                'db_table': 'announcements',
                'ordering': ['-published_at'],
            },
        ),
    ]
