# Generated by Django 5.1.15 on 2026-10-02 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TEAMWORK', 'Teamwork'), ('INNOVATION', 'Innovation'), ('LEADERSHIP', 'Leadership'), ('PROBLEM_SOLVING', 'Problem Solving'), ('CUSTOMER_FOCUS', 'Customer Focus'), ('LEARNING', 'Learning')], max_length=20)),
                ('badge', models.CharField(choices=[('PROBLEM_SOLVER', 'Problem Solver'), ('TEAM_PLAYER', 'Team Player'), ('INNOVATOR', 'Innovator'), ('LEADER', 'Leader'), ('FAST_LEARNER', 'Fast Learner')], max_length=20)),
                ('message', models.CharField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions_given', to='employees.employee')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognitions', to='employees.employee')),
            ],
            options={
                'db_table': 'recognitions',
                'ordering': ['-created_at'],
            },
        ),
    ]
